def expand_types(types: list[type]) -> list[list[type]]: ...
def get_max_args() -> int: ...
def set_max_args(m: int) -> None: ...
def dyn_dispatch(class_type, method_name, *types): ...
def dyn_method(f): ...
def dyn_dispatch_f(fun_name, *types): ...
def dyn_fun(f): ...
